/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionTimbiriche;

/**
 *
 * @author cesar
 */
public class frmCrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public frmCrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCrearCuenta = new javax.swing.JPanel();
        lbltituloCrearcuenta = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        lblTituloCorreoElectronico = new javax.swing.JLabel();
        lblNumeroCelular = new javax.swing.JLabel();
        lbTituloNombreUsuario = new javax.swing.JLabel();
        jpImagenJugador = new javax.swing.JPanel();
        btnCargarUsuario = new javax.swing.JButton();
        lblTituloDescripImagen1 = new javax.swing.JLabel();
        btnCrearcuenta = new javax.swing.JButton();
        btnAvatarUsuario = new javax.swing.JButton();
        lblTituloDescripImagen2 = new javax.swing.JLabel();
        btnVolverCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCrearCuenta.setBackground(new java.awt.Color(153, 153, 153));
        jpCrearCuenta.setMinimumSize(new java.awt.Dimension(900, 500));
        jpCrearCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltituloCrearcuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbltituloCrearcuenta.setText("CREAR CUENTA");
        jpCrearCuenta.add(lbltituloCrearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));
        jpCrearCuenta.add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 260, 230, -1));

        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        jpCrearCuenta.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 230, -1));
        jpCrearCuenta.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 230, -1));

        lblTituloCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloCorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCorreoElectronico.setText("Correo Electronico");
        jpCrearCuenta.add(lblTituloCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        lblNumeroCelular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumeroCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroCelular.setText("Numero Celular");
        jpCrearCuenta.add(lblNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        lbTituloNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTituloNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloNombreUsuario.setText("Nombre");
        jpCrearCuenta.add(lbTituloNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        javax.swing.GroupLayout jpImagenJugadorLayout = new javax.swing.GroupLayout(jpImagenJugador);
        jpImagenJugador.setLayout(jpImagenJugadorLayout);
        jpImagenJugadorLayout.setHorizontalGroup(
            jpImagenJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jpImagenJugadorLayout.setVerticalGroup(
            jpImagenJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jpCrearCuenta.add(jpImagenJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 180, 220));

        btnCargarUsuario.setText("Cargar");
        jpCrearCuenta.add(btnCargarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, -1));

        lblTituloDescripImagen1.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDescripImagen1.setText("Seleccione un Avatar o bien haga");
        jpCrearCuenta.add(lblTituloDescripImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, -1, -1));

        btnCrearcuenta.setText("CREAR CUENTA");
        btnCrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearcuentaActionPerformed(evt);
            }
        });
        jpCrearCuenta.add(btnCrearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 200, 50));

        btnAvatarUsuario.setText("Avatar");
        jpCrearCuenta.add(btnAvatarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        lblTituloDescripImagen2.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDescripImagen2.setText("click en \"cargar\" si desea añadir una imagen de perfil ");
        jpCrearCuenta.add(lblTituloDescripImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        btnVolverCrearCuenta.setText("Volver");
        btnVolverCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverCrearCuentaActionPerformed(evt);
            }
        });
        jpCrearCuenta.add(btnVolverCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCrearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void btnCrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearcuentaActionPerformed
frmInicio ini=new frmInicio();
ini.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearcuentaActionPerformed

    private void btnVolverCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverCrearCuentaActionPerformed
       frmInicio ini= new frmInicio();
       ini.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVolverCrearCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvatarUsuario;
    private javax.swing.JButton btnCargarUsuario;
    private javax.swing.JButton btnCrearcuenta;
    private javax.swing.JButton btnVolverCrearCuenta;
    private javax.swing.JPanel jpCrearCuenta;
    private javax.swing.JPanel jpImagenJugador;
    private javax.swing.JLabel lbTituloNombreUsuario;
    private javax.swing.JLabel lblNumeroCelular;
    private javax.swing.JLabel lblTituloCorreoElectronico;
    private javax.swing.JLabel lblTituloDescripImagen1;
    private javax.swing.JLabel lblTituloDescripImagen2;
    private javax.swing.JLabel lbltituloCrearcuenta;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumeroCelular;
    // End of variables declaration//GEN-END:variables
}
