/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PresentacionTimbiriche;

/**
 *
 * @author cesar
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInicio = new javax.swing.JPanel();
        lbTituloiniciarSeion = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        lbNombreUsuario = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JLabel();
        btnEntrarinicio = new javax.swing.JButton();
        lblTituloNoTienesCuenta = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        lblLogoTim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpInicio.setBackground(new java.awt.Color(0, 0, 0));
        jpInicio.setMinimumSize(new java.awt.Dimension(900, 500));
        jpInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTituloiniciarSeion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTituloiniciarSeion.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloiniciarSeion.setText("Iniciar Sesion");
        jpInicio.add(lbTituloiniciarSeion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));
        jpInicio.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 170, -1));
        jpInicio.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 170, -1));

        lbNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreUsuario.setText("Nombre de usuario");
        jpInicio.add(lbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        lbContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lbContraseña.setText("Contraseña");
        jpInicio.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        btnEntrarinicio.setText("ENTRAR");
        btnEntrarinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarinicioActionPerformed(evt);
            }
        });
        jpInicio.add(btnEntrarinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 110, 40));

        lblTituloNoTienesCuenta.setForeground(new java.awt.Color(255, 51, 51));
        lblTituloNoTienesCuenta.setText("¿No tienes cuenta?");
        jpInicio.add(lblTituloNoTienesCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        jpInicio.add(btnCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        lblLogoTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logonuevo.jpg"))); // NOI18N
        jpInicio.add(lblLogoTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
frmCrearCuenta crear= new frmCrearCuenta();
crear.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void btnEntrarinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarinicioActionPerformed
      frmMenu menu=new frmMenu();
      menu.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnEntrarinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnEntrarinicio;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbTituloiniciarSeion;
    private javax.swing.JLabel lblLogoTim;
    private javax.swing.JLabel lblTituloNoTienesCuenta;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
